/**
 * Status Constants
 */
export const PASS_STATUS = {
  PENDING_DEPARTMENT: "PENDING_DEPARTMENT",
  PENDING_ACADEMIC: "PENDING_ACADEMIC",
  PENDING_HOSTEL: "PENDING_HOSTEL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
};

export const APPROVAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  N_A: "N/A",
};

